
[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/Cisco-Talos/onenote.rs.git?branch=CLAM-2329-new-from-slice"]
git = "https://github.com/Cisco-Talos/onenote.rs.git"
branch = "CLAM-2329-new-from-slice"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = ".cargo/vendor"

